### ISSUE TITLE
Properties file ignores keys with empty values

### ISSUE THREAD

**Issue by ajays20078** [ssato/python-anyconfig#51] opened 2016-09-17 11:58 UTC
Loading and dumping a properties file having a  empty value is ignoring the key, and dumps without the keys having empty value.

Example:

File name : /tmp/1.properties

Content:

```
username = "my_db_user"
password = 
```

```
>>> import anyconfig
>>> a = anyconfig.load("/tmp/1.properties")
>>> a
{'username': '"my_db_user"'}
>>> 
```

This can  cause issues, when reading the file dumped using anyconfig. There are many open source software, which uses [this](https://github.com/pinterest/secor/blob/f2b182581538a6c4ef3b53f0efcddde6303bdb1e/src/main/config/secor.dev.properties#L13) feature to load default values if key is empty(key is present but empty) and they error out if key is not present. 

Also `""` or `''` are not treated as empty by properties file, they are treated as strings as per the documentation [here](https://en.wikipedia.org/wiki/.properties) (so currently there is no way to specify empty values using anyconfig), so  can anyconfig support loading and dumping empty values as it could break code which expects a key(which can be empty).

**Comment by ajays20078** [comment] 2016-09-23 11:58
Any updates on this?

**Comment by ssato** [comment] 2016-09-23 14:40
Sorry, I've been very busy this week and don't have enough time to look at this.

At first glance, I guess your point the problem is absolutely right. Thanks a lot for that.
But I want to take some time to look into this issue as same as #50 this weekend.
Please wait for a while.

**Comment by ssato** [comment] 2016-09-24 16:49
I think I could fix this issue by 5555bbd (properties branch). Could you please take a look at it?

**Comment by ssato** [comment] 2016-09-24 17:11
FYI. I merged the related (possible) fixes in properties branch to master branch.

**Comment by ajays20078** [comment] 2016-09-26 07:23
Thanks for the update and PR. Will checkout master and revert back.

**Comment by ajays20078** [comment] 2016-09-26 10:02
Works as expected. Thanks!

**Closed** 2016-09-27 09:12 UTC
